import mongoose from "mongoose";
import dotenv from "dotenv";
import fs from "fs";
import path from "path";
import XLSX from "xlsx";

dotenv.config();

import Customer from "../model/customerModel.js";
import { findMatchingCustomer } from "../controller/importController.js";

const normalizeStr = (str) => {
  if (!str) return "";
  return String(str)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
};

async function runBackfill() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log("Connected to MongoDB for backfill.");

  const allCustomers = await Customer.find();
  console.log(`Total customers in DB: ${allCustomers.length}`);

  const importsDir = path.resolve("uploads/imports");
  const files = fs.readdirSync(importsDir).filter((f) => f.endsWith(".xlsx"));

  const jobNoMap = new Map(); // key: customerId string, val: jobNo

  for (const file of files) {
    const filePath = path.join(importsDir, file);
    try {
      const wb = XLSX.readFile(filePath, { sheetStubs: true });
      for (const sheetName of wb.SheetNames) {
        const sheet = wb.Sheets[sheetName];
        const rows = XLSX.utils.sheet_to_json(sheet, { defval: "" });
        if (!rows || rows.length === 0) continue;

        // Search row keys for job no, client name, address, phone
        for (const row of rows) {
          let jobNoVal = "";
          let nameVal = "";
          let addrVal = "";
          let phoneVal = "";

          for (const key of Object.keys(row)) {
            const kUpper = key.trim().toUpperCase();
            if (kUpper === "JOB NO" || kUpper === "JOB NO." || kUpper === "JOB_NO" || kUpper === "JOB NUMBER") {
              jobNoVal = String(row[key]).trim();
            } else if (kUpper.includes("CLIENT NAME") || kUpper.includes("PARTY NAME") || kUpper === "FULL NAME" || kUpper === "NAME") {
              nameVal = String(row[key]).trim();
            } else if (kUpper.includes("ADDRESS") || kUpper.includes("LOCATION") || kUpper.includes("SITE LOCATION")) {
              if (!addrVal) addrVal = String(row[key]).trim();
            } else if (kUpper.includes("MOB") || kUpper.includes("PHONE") || kUpper.includes("CONTACT NUMBER")) {
              phoneVal = String(row[key]).trim();
            }
          }

          if (jobNoVal && (nameVal || phoneVal || addrVal)) {
            // Find matching customer in allCustomers list
            const matched = findMatchingCustomer(nameVal, phoneVal, "", addrVal, allCustomers);
            if (matched) {
              if (!jobNoMap.has(matched._id.toString())) {
                jobNoMap.set(matched._id.toString(), jobNoVal);
              }
            }
          }
        }
      }
    } catch (e) {
      console.error(`Error reading ${file}:`, e.message);
    }
  }

  console.log(`Matched ${jobNoMap.size} customers with JOB NOs from Excel files.`);

  let updatedCount = 0;
  for (const [custId, jNo] of jobNoMap.entries()) {
    await Customer.findByIdAndUpdate(custId, { jobNo: jNo });
    updatedCount++;
  }
  console.log(`Updated ${updatedCount} customers with JOB NO from Excel.`);

  // Now handle any remaining customers that don't have a jobNo yet
  const remainingCustomers = await Customer.find({
    $or: [{ jobNo: { $exists: false } }, { jobNo: "" }, { jobNo: null }],
  });

  console.log(`Customers still needing JOB NO auto-generation: ${remainingCustomers.length}`);

  // Auto-generate JOB NOs grouped by initial prefix (A/01, A/02, B/01...)
  const prefixCounters = new Map();

  // Pre-fill prefixCounters with max numbers from already assigned jobNos
  const currentCustomersWithJobNo = await Customer.find({
    jobNo: { $exists: true, $ne: "" },
  });

  for (const cust of currentCustomersWithJobNo) {
    const match = cust.jobNo ? cust.jobNo.match(/^([A-Z])\/(\d+)$/i) : null;
    if (match) {
      const prefix = match[1].toUpperCase();
      const num = parseInt(match[2], 10);
      const curMax = prefixCounters.get(prefix) || 0;
      if (num > curMax) prefixCounters.set(prefix, num);
    }
  }

  let autoGeneratedCount = 0;
  for (const cust of remainingCustomers) {
    const initial = (cust.fullName && cust.fullName.trim().charAt(0).toUpperCase()) || "C";
    const prefix = /^[A-Z]$/.test(initial) ? initial : "C";
    const currentNum = (prefixCounters.get(prefix) || 0) + 1;
    prefixCounters.set(prefix, currentNum);

    const generatedJobNo = `${prefix}/${String(currentNum).padStart(2, "0")}`;
    await Customer.findByIdAndUpdate(cust._id, { jobNo: generatedJobNo });
    autoGeneratedCount++;
  }

  console.log(`Auto-generated JOB NO for ${autoGeneratedCount} remaining customers.`);

  const finalTotal = await Customer.countDocuments({ jobNo: { $exists: true, $ne: "" } });
  console.log(`Final Total Customers with JOB NO: ${finalTotal}`);

  await mongoose.disconnect();
  console.log("Backfill completed successfully.");
}

runBackfill().catch(console.error);
